### ISSUE TITLE
use with elasticsearch

### ISSUE THREAD

**Issue by perlish** [msarhan/lucene-arabic-analyzer#1]
hi
it's great library, is it possible to use this library as default arabic analyzer with elastic search?
if it's possible how? do i have to compile elastic search with this library?

thanks for your attention

**Comment by sorakun** [comment]
Hello, this library is for Lucene, you can simply use it with elasticsearch by registerting it as a plugin. I have used it in solr and works great, never tried elasticsearch but it should be the same.
