### ISSUE TITLE
Text Field length in lucene arabic analyzer document  

### ISSUE THREAD

**Issue by MohamedSamirShabaan** [msarhan/lucene-arabic-analyzer#2]
- I use the library it's most helpful ,  but i face a problem about the field length i get a exception when i try to index long field title , How to make it unlimited?

- e.g:
doc = new Document();
doc.add(new StringField("number", "0", Field.Store.YES));
doc.add(new TextField("title", "طلعلتي غده بالرقبه واكلت اوجمنتين اسبوع ولكن لم تذهب ورحت عملت اشعه وتبين انها عده لمفاويه وقال لي الطبيب انها امر عادي تذهب من تلقاء نفسها اماتكون سببها فروة الرأس ام الاذن", Field.Store.YES));
writer.addDocument(doc);*/

result : is exception array out of index !

**Comment by msarhan** [comment]
The code you provided is not using lucene-arabic-analyzer components!
Please to provide the full code section with the complete stack trace of the exception.

**Comment by MohamedSamirShabaan** [comment]
import java.io.IOException;
import org.apache.lucene.analysis.Analyzer;
import org.apache.lucene.document.Document;
import org.apache.lucene.document.StringField;
import org.apache.lucene.index.IndexWriter;
import org.apache.lucene.index.IndexWriterConfig;
import org.apache.lucene.queryparser.classic.ParseException;
import org.apache.lucene.store.Directory;
import org.apache.lucene.store.RAMDirectory;
import org.apache.lucene.document.Field;
import org.apache.lucene.document.TextField;

import com.github.msarhan.lucene.ArabicRootExtractorAnalyzer;

public class test {
	
	

	public static void main(String[] args) throws IOException, ParseException {
		// TODO Auto-generated method stub
		Directory index = new RAMDirectory();
		Analyzer analyzer = new ArabicRootExtractorAnalyzer();
		IndexWriterConfig config = new IndexWriterConfig(analyzer);
		IndexWriter writer = new IndexWriter(index, config );

		Document doc = new Document();
		doc.add(new StringField("number", "1", Field.Store.YES));
		doc.add(new TextField("title", "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ", Field.Store.YES));
		writer.addDocument(doc);
			
		
		doc = new Document();
		doc.add(new StringField("number", "2", Field.Store.YES));
		doc.add(new TextField("title", "طلعلتي غده بالرقبه واكلت اوجمنتين اسبوع ولكن لم تذهب ورحت عملت اشعه وتبين انها عده لمفاويه وقال لي الطبيب انها امر عادي تذهب من تلقاء نفسها اماتكون سببها فروة الرأس ام الاذن", Field.Store.YES));
		writer.addDocument(doc);
		
		writer.close();
	``	
	}
}

**Comment by MohamedSamirShabaan** [comment]
i think the problem not in the length of code but  it's in "ام" when i remove it , it work correctly ? even if the length is more.

**Comment by MohamedSamirShabaan** [comment]
Sorry about the Disturbance , i think you update it in new release 1.1.2 but i used 1.0.1
