### ISSUE TITLE
Khoja stemmer fails on some words

### ISSUE THREAD

**Issue by hwasiti** [msarhan/lucene-arabic-analyzer#4]
It seems there is another Java program that has a much better Arabic stemmer in comparison to the  Khoja stemmer:
برنامج الخليل الصّرفي 2
- web app: [http://toolkit.oujda-nlp-team.net/AlKhalil2/](http://toolkit.oujda-nlp-team.net/AlKhalil2/)
- Java source code and JAR: [http://oujda-nlp-team.net/ar/programms-ar/alkhalil-morphology-2-ar/](http://oujda-nlp-team.net/ar/programms-ar/alkhalil-morphology-2-ar/)

For example, try in the web app above to find the roots for the word:
قال

you will find that it will generate 5 different roots. That's because the word has multiple different meanings in Arabic (spoke, took a nap which is the past tense of the verb to take قيلولة,...etc.)

I tried your Java code and it gave only the root 
قول

Another example:
Try the word قيلولة
in the web app. It will give the root قيل
which is correct.

But I tried it in your code and the stemmer resulted with قيلولة
which is not the root.

So if the search query is قيلولة
Lucene will not find the associated verbs like: يقيل ، قال
Because with the Khoja stemmer these words have different roots, but actually they should have the same root since they all describe taking a nap.

Maybe you can consider using the Java stemmer code of
برنامج الخليل الصّرفي 2
in the future instead of the Khoja stemmer. Finding correct roots is key for a good search engine. And Arabic roots are tricky!

**Comment by msarhan** [comment]
@hwasiti Thank you very much,
I'll check this library and try using it in the coming release.

**Comment by msarhan** [comment]
Now version 2.x uses برنامج الخليل الصّرفي 2
Thanks for your suggestion.
